definitions:
  app.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        description: Optional, can be empty
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/anonymous:
    post:
      consumes:
      - application/json
      description: Create an anonymous access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.LoginResponse'
      summary: Anonymous Log In
      tags:
      - auth
swagger: "2.0"
