definitions:
  chords_com_api_internal_entity.Room:
    properties:
      code:
        type: string
      created_at:
        type: string
      deleted_at:
        allOf:
        - $ref: '#/definitions/gorm.DeletedAt'
        description: Use pointer to allow null values
      id:
        type: integer
      ownerID:
        type: integer
      updated_at:
        type: string
      users:
        items:
          $ref: '#/definitions/chords_com_api_internal_entity.User'
        type: array
    type: object
  chords_com_api_internal_entity.User:
    properties:
      created_at:
        type: string
      deleted_at:
        allOf:
        - $ref: '#/definitions/gorm.DeletedAt'
        description: Use pointer to allow null values
      id:
        type: integer
      isAnonymous:
        type: boolean
      myRooms:
        items:
          $ref: '#/definitions/chords_com_api_internal_entity.Room'
        type: array
      rooms:
        items:
          $ref: '#/definitions/chords_com_api_internal_entity.Room'
        type: array
      updated_at:
        type: string
    type: object
  chords_com_api_internal_event_bus.Event:
    properties:
      data: {}
      origin:
        type: integer
      type:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_app.JoinRoomRequest:
    properties:
      room_code:
        type: string
    type: object
  internal_app.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        description: Optional, can be empty
        type: string
    type: object
  internal_app.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/anonymous:
    post:
      consumes:
      - application/json
      description: Create an anonymous access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app.LoginResponse'
      summary: Anonymous Log In
      tags:
      - auth
  /api/auth/refresh-token:
    post:
      description: Refresh an access token using a refresh token
      parameters:
      - description: Refresh Token Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_app.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app.LoginResponse'
      summary: Refresh Access Token
      tags:
      - auth
  /api/rooms:
    post:
      consumes:
      - application/json
      description: Create a new room with a unique code and add the user to it.
      produces:
      - application/json
      responses:
        "201":
          description: Room created successfully
          schema:
            $ref: '#/definitions/chords_com_api_internal_entity.Room'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create a new room
      tags:
      - rooms
  /api/rooms/{id}/leave:
    post:
      consumes:
      - application/json
      description: Leave a room using the room ID.
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Room left successfully
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Room Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Leave a room
      tags:
      - rooms
  /api/rooms/join:
    post:
      consumes:
      - application/json
      description: Join a room using the room code.
      parameters:
      - description: Join Room Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_app.JoinRoomRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Room joined successfully
          schema:
            $ref: '#/definitions/chords_com_api_internal_entity.Room'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Room Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Join a room
      tags:
      - rooms
  /ws:
    post:
      consumes:
      - application/json
      description: This is a placeholder - only for OpenAPI documentation purposes.
      parameters:
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/chords_com_api_internal_event_bus.Event'
      produces:
      - application/json
      responses:
        "200":
          description: WebSocket event
          schema:
            $ref: '#/definitions/chords_com_api_internal_event_bus.Event'
      security:
      - BearerAuth: []
      summary: Post WebSocket Handler
      tags:
      - WebSocket
swagger: "2.0"
