services:
  api:
    image: mychords/api:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - default

  app:
    image: mychords/app:latest
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - api

networks:
  default:
    driver: bridge
    name: chords_network
