version: "3.8"

services:
  mychords-api:
    image: mychords-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./data/api:/data
    expose:
      - "8080"
    networks:
      - default

  mychords-app:
    image: mychords-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - mychords-api

networks:
  default:
    driver: bridge
    name: serva4ok_network
