version: "3.8"

services:
  api:
    image: mychords-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./data/api:/data
    expose:
      - "8080"
    networks:
      - mychords-network

  app:
    image: mychords-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "2019:2019" # Caddy admin port
    networks:
      - mychords-network
    depends_on:
      - api

networks:
  mychords-network:
    driver: bridge
