package app

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	_ "chords.com/api/docs" // docs is generated by Swag CLI, you have to import it.

	"chords.com/api/internal/auth"
	"chords.com/api/internal/orm"
)

func NewHttpRouter(a *App) *chi.Mux {
	r := chi.NewRouter()

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})

	r.Get("/swagger/*", func(w http.ResponseWriter, r *http.Request) {
		protocol := "http"
		if r.TLS != nil {
			protocol = "https"
		}
		httpSwagger.Handler(
			httpSwagger.URL(protocol+"://"+r.Host+"/swagger/doc.json"),
		).ServeHTTP(w, r)
	})

	r.Group(func(r chi.Router) {
		r.Use(middleware.RequestID)
		r.Use(middleware.RealIP)
		r.Use(middleware.Logger)
		r.Use(middleware.Recoverer)

		r.Group(func(r chi.Router) {
			r.Use(auth.Middleware)
			r.Handle("/ws", a.NewWSHandler())
			r.Post("/ws", a.PostWSHandler)
		})

		r.Route("/api", func(r chi.Router) {
			r.Use(orm.Middleware)

			r.Post("/auth/anonymous", a.AnonymousLogIn)
			r.Post("/auth/refresh-token", a.RefreshToken)

			r.Group(func(r chi.Router) {
				r.Use(auth.Middleware)

				r.Post("/rooms", a.CreateRoom)
				r.Post("/rooms/join", a.JoinRoom)
				r.Post("/rooms/{id}/leave", a.LeaveRoom)
			})
		})
	})

	return r
}
