port: 8080
sqlite_file: ../data/prod.sqlite
secret: topsecret
access_token_expires_in_seconds: 86400
confirmation_link: "http://localhost:8080/confirm/{code}"

# dev | prod
logger_env: dev

# debug | info | warn | error
logger_level: debug
logger_levels:
  db: debug
  client: debug
