# syntax=docker/dockerfile:1

FROM golang:1.25-alpine

WORKDIR /app

ENV CGO_ENABLED=1
# Install gcc for cgo support and air for hot reload
RUN apk add --no-cache gcc musl-dev

RUN go install github.com/swaggo/swag/cmd/swag@v1.16.4
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
